### PR TITLE
Add Archlinux Support For Dependencies

### PR DESCRIPTION
**Pull request by MrSwedish**

### CODE REVIEW

**Comment by SuperPou1** [comment]
Nice!

**Comment by MrSwedish** [comment]
thanks

**Comment by MrSwedish** [comment]
1 more thing you gotta do:
add
```
#!/usr/bin/python3
```
to the beginning of launcher.py and themeconfig.py
and in the readme in the bottom of the desktop entry section
replace
```
python3 /home/superpou1/mariolauncher/launcher.py
```
with
```
./launcher.py
```

**Comment by MrSwedish** [comment]
I'll make another pull request if you don't see this
or if you want it

**Comment by MrSwedish** [comment]
> 1 more thing you gotta do:
> add
> 
> ```
> #!/usr/bin/python3
> ```
> 
> to the beginning of launcher.py and themeconfig.py ( like in [976a91d](https://github.com/SuperPou1/sm64pclauncher/commit/976a91db9f91e7fceafec804af26216f53ccd9a9) )
> and in the readme in the bottom of the desktop entry section
> replace
> 
> ```
> && python3 /home/superpou1/mariolauncher/launcher.py
> ```
> 
> with
> 
> ```
> ; ./launcher.py
> ```
newest pull request does this

**Pull request merged**
